// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPuziA3Ucdx9p6uQvB19WGsObPu0z24dY',
    appId: '1:854327113981:web:217645af38e721b0916694',
    messagingSenderId: '854327113981',
    projectId: 'bazarapp-8aa8d',
    authDomain: 'bazarapp-8aa8d.firebaseapp.com',
    storageBucket: 'bazarapp-8aa8d.appspot.com',
    measurementId: 'G-23GRNCCRZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBacdjTONENct56nKnzbNQZCw8xmMvzsDA',
    appId: '1:854327113981:android:752ef512c36ce876916694',
    messagingSenderId: '854327113981',
    projectId: 'bazarapp-8aa8d',
    storageBucket: 'bazarapp-8aa8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzXcBBboz-35LCmwh9u-0OIKq3ds7Bvo',
    appId: '1:854327113981:ios:65532a384231182c916694',
    messagingSenderId: '854327113981',
    projectId: 'bazarapp-8aa8d',
    storageBucket: 'bazarapp-8aa8d.appspot.com',
    iosBundleId: 'com.example.bazarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzXcBBboz-35LCmwh9u-0OIKq3ds7Bvo',
    appId: '1:854327113981:ios:65532a384231182c916694',
    messagingSenderId: '854327113981',
    projectId: 'bazarapp-8aa8d',
    storageBucket: 'bazarapp-8aa8d.appspot.com',
    iosBundleId: 'com.example.bazarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPuziA3Ucdx9p6uQvB19WGsObPu0z24dY',
    appId: '1:854327113981:web:ff2163b31c192fa8916694',
    messagingSenderId: '854327113981',
    projectId: 'bazarapp-8aa8d',
    authDomain: 'bazarapp-8aa8d.firebaseapp.com',
    storageBucket: 'bazarapp-8aa8d.appspot.com',
    measurementId: 'G-QC9WS7JL7V',
  );
}
